matrix:
  include:
    - os: windows
      language: node_js
      node_js: "node"
    - os: linux
      dist: xenial
      services:
        - xvfb
      language: node_js
      node_js: "node"

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

branches:
  only:
  - master
  - develop
  - feature/travis_ci

script:
- |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      npm run dist -w
    else
      npm test && npm run dist -lm
    fi

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Yury Ivannikov"
  - git config --local user.email "yuryivannikov@yandex.ru"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - "dist/yamusuc-*.dmg"
    - "dist/YaMusic Setup*.exe"
    - "dist/YaMusic_*.snap"
  skip_cleanup: true
  draft: true
    branches:
    only:
      - master
      - feature/travis_ci