matrix:
  include:
    - os: windows
      language: node_js
      node_js: "node"
    - os: linux
      dist: xenial
      services:
        - xvfb
      language: node_js
      node_js: "node"

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    
branches:
  only:
  - master
  - develop
  - feature/travis_ci

script:
- npm test
- |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      npm run dist -w
    else
      npm run dist -lm
    fi